### ISSUE TITLE
 Images Not Showing on Deployed App on Render

### ISSUE THREAD

**Issue by janel2411** [janel2411/tradewise#4]
Description
Images and other static files (eg whole React Quiz App feature) are not showing on the deployed application on Render, but they are visible on the development server. The issue needs to be resolved to ensure proper display of images in production.

Screenshots
Development Server (Working):
<img width="1344" alt="Screenshot 2024-07-01 at 12 39 48 PM" src="https://github.com/janel2411/tradewise/assets/170722447/d9b5bddf-2897-4acb-8bfe-1206c8a67b03">

Deployed Server on Render (Not Working):
<img width="613" alt="Screenshot 2024-07-01 at 12 37 59 PM" src="https://github.com/janel2411/tradewise/assets/170722447/ee2bc362-be0a-4798-a90e-63defae2727d">

Steps to Reproduce
Deploy the Django application on Render.
Navigate to the homepage or any other page where images should be displayed.
Navigate to the Quiz tab.

Expected Behaviour: Images should be displayed correctly on the deployed application, as they are on the development server. Quiz 1 should be live and functional.

Actual Behaviour: Images and quiz app, which are all loaded using static files, are not displayed on the deployed application.

**Comment by kkaizee** [comment]
Tried deploying with a different host, Vercel, and faced this error.

Error: No Output Directory named "build" found after the Build completed. You can configure the Output Directory in your Project Settings.

**Comment by kkaizee** [comment]
Fixed
